#!/usr/bin/env bash
# =============================================================================
# post-install.sh - Post-installation tasks
# =============================================================================
# Sourced by bootstrap.sh. Provides the post_install function.
# =============================================================================

# ---------------------------------------------------------------------------
# post_install - Run post-installation tasks
# ---------------------------------------------------------------------------
# Arguments:
#   $1 - target_path  (target project root)
#   $2 - stack        (stack name for summary)
# ---------------------------------------------------------------------------
post_install() {
    local target_path="$1"
    local stack="$2"

    # Make all .sh files executable
    _post_install_chmod_scripts "${target_path}"

    # Update .gitignore
    _post_install_update_gitignore "${target_path}"

    # Create .gitkeep files for empty directories
    _post_install_create_gitkeeps "${target_path}"

    # Print summary
    _post_install_print_summary "${target_path}" "${stack}"

    # Print next steps
    _post_install_print_next_steps "${target_path}" "${stack}"
}

# ---------------------------------------------------------------------------
# _post_install_chmod_scripts - Make all .sh files in .claude/ executable
# ---------------------------------------------------------------------------
_post_install_chmod_scripts() {
    local target_path="$1"
    local claude_dir="${target_path}/.claude"

    local count=0
    while IFS= read -r -d '' sh_file; do
        chmod +x "${sh_file}"
        count=$((count + 1))
    done < <(find "${claude_dir}" -name "*.sh" -type f -print0 2>/dev/null)

    if [[ ${count} -gt 0 ]]; then
        log_substep "Made ${count} script(s) executable"
    fi
}

# ---------------------------------------------------------------------------
# _post_install_update_gitignore - Add agent directories to .gitignore
# ---------------------------------------------------------------------------
_post_install_update_gitignore() {
    local target_path="$1"
    local gitignore="${target_path}/.gitignore"

    local entries=".agent-status/ .agent-pipeline/ .agent-eval-results/ .claude/context/active-work.md"

    # Create .gitignore if it doesn't exist
    if [[ ! -f "${gitignore}" ]]; then
        touch "${gitignore}"
        log_substep "Created .gitignore"
    fi

    local added=0
    for entry in ${entries}; do
        # Check if entry already exists in .gitignore (exact line match)
        if ! grep -qxF "${entry}" "${gitignore}" 2>/dev/null; then
            # Add a newline before our section if file doesn't end with one
            if [[ -s "${gitignore}" ]]; then
                # Check if file ends with newline
                if [[ "$(tail -c 1 "${gitignore}" | wc -l)" -eq 0 ]]; then
                    echo "" >> "${gitignore}"
                fi
            fi

            # Add section header on first addition
            if [[ ${added} -eq 0 ]]; then
                echo "" >> "${gitignore}"
                echo "# Agent pipeline (generated by agents template generator)" >> "${gitignore}"
            fi

            echo "${entry}" >> "${gitignore}"
            added=$((added + 1))
        fi
    done

    if [[ ${added} -gt 0 ]]; then
        log_substep "Added ${added} entries to .gitignore"
    else
        log_substep ".gitignore already up to date"
    fi
}

# ---------------------------------------------------------------------------
# _post_install_create_gitkeeps - Create .gitkeep files for empty directories
# ---------------------------------------------------------------------------
_post_install_create_gitkeeps() {
    local target_path="$1"

    local context_features_dir="${target_path}/.claude/context/features"

    for dir in "${context_features_dir}"; do
        mkdir -p "${dir}"
        if [[ ! -f "${dir}/.gitkeep" ]]; then
            touch "${dir}/.gitkeep"
        fi
    done

    log_substep "Created .gitkeep files for empty directories"
}

# ---------------------------------------------------------------------------
# _post_install_print_summary - Print summary of what was installed
# ---------------------------------------------------------------------------
_post_install_print_summary() {
    local target_path="$1"
    local stacks="$2"
    local claude_dir="${target_path}/.claude"

    # Format stacks display (replace commas with " + ")
    local stacks_display="${stacks//,/ + }"

    echo ""
    echo -e "${BOLD}  Installation Summary${NC}"
    echo -e "${DIM}  ────────────────────────────────────────${NC}"
    echo -e "  Stacks:  ${CYAN}${stacks_display}${NC}"
    echo -e "  Target:  ${CYAN}${target_path}${NC}"
    echo ""

    # Count installed items
    local agent_count=0
    local skill_count=0
    local hook_count=0
    local pattern_count=0
    local style_count=0

    if [[ -d "${claude_dir}/agents" ]]; then
        agent_count=$(find "${claude_dir}/agents" -maxdepth 1 -type f 2>/dev/null | wc -l | tr -d ' ')
    fi
    if [[ -d "${claude_dir}/skills" ]]; then
        skill_count=$(find "${claude_dir}/skills" -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
        skill_count=$((skill_count > 0 ? skill_count - 1 : 0))  # Subtract the directory itself
    fi
    if [[ -d "${claude_dir}/hooks" ]]; then
        hook_count=$(find "${claude_dir}/hooks" -maxdepth 1 -type f 2>/dev/null | wc -l | tr -d ' ')
    fi
    if [[ -d "${claude_dir}/patterns" ]]; then
        pattern_count=$(find "${claude_dir}/patterns" -maxdepth 1 -type f 2>/dev/null | wc -l | tr -d ' ')
    fi
    if [[ -d "${claude_dir}/styles" ]]; then
        style_count=$(find "${claude_dir}/styles" -maxdepth 1 -type f 2>/dev/null | wc -l | tr -d ' ')
    fi

    echo -e "  ${GREEN}Installed:${NC}"
    echo -e "    Agents:    ${BOLD}${agent_count}${NC}"
    echo -e "    Skills:    ${BOLD}${skill_count}${NC}"
    echo -e "    Hooks:     ${BOLD}${hook_count}${NC}"
    echo -e "    Patterns:  ${BOLD}${pattern_count}${NC}"
    echo -e "    Styles:    ${BOLD}${style_count}${NC}"

    # List installed files
    if [[ -f "${target_path}/CLAUDE.md" ]]; then
        echo -e "    CLAUDE.md: ${GREEN}yes${NC}"
    fi
    if [[ -f "${claude_dir}/settings.json" ]]; then
        echo -e "    settings.json: ${GREEN}yes${NC}"
    fi
    if [[ -f "${claude_dir}/settings.local.json" ]]; then
        echo -e "    settings.local.json: ${GREEN}yes${NC}"
    fi

    echo ""

    # List skill names if any
    if [[ ${skill_count} -gt 0 ]]; then
        echo -e "  ${GREEN}Available Skills:${NC}"
        for skill_dir in "${claude_dir}/skills"/*/; do
            if [[ -d "${skill_dir}" ]]; then
                local skill_name
                skill_name="$(basename "${skill_dir}")"
                echo -e "    ${CYAN}/${skill_name}${NC}"
            fi
        done
        echo ""
    fi
}

# ---------------------------------------------------------------------------
# _post_install_print_next_steps - Print next steps for the user
# ---------------------------------------------------------------------------
_post_install_print_next_steps() {
    local target_path="$1"
    local stacks="$2"

    # Format stacks for commit message
    local stacks_display="${stacks//,/ + }"

    echo -e "${BOLD}  Next Steps${NC}"
    echo -e "${DIM}  ────────────────────────────────────────${NC}"
    echo ""
    echo -e "  1. ${BOLD}Review the configuration:${NC}"
    echo -e "     ${DIM}cd ${target_path}${NC}"
    echo -e "     ${DIM}cat CLAUDE.md${NC}"
    echo -e "     ${DIM}ls .claude/${NC}"
    echo ""
    echo -e "  2. ${BOLD}Customize settings:${NC}"
    echo -e "     ${DIM}Edit .claude/settings.json for project-wide settings${NC}"
    echo -e "     ${DIM}Edit .claude/settings.local.json for personal overrides${NC}"
    echo ""
    echo -e "  3. ${BOLD}Add feature context:${NC}"
    echo -e "     ${DIM}Create files in .claude/context/features/ to track features${NC}"
    echo ""
    echo -e "  4. ${BOLD}Start using agents:${NC}"
    echo -e "     ${DIM}Open the project in Claude Code and start working!${NC}"
    echo -e "     ${DIM}Use skills by typing /<skill-name> in the chat.${NC}"
    echo ""
    echo -e "  5. ${BOLD}Commit the configuration:${NC}"
    echo -e "     ${DIM}git add .claude/ CLAUDE.md .gitignore${NC}"
    echo -e "     ${DIM}git commit -m \"Add Claude Code agent configuration (${stacks_display})\"${NC}"
    echo ""
}
