name: fastapi
display_name: Python FastAPI
description: Backend development with Python FastAPI

default_model: opus

compatible_with:
  - nextjs
  - react-native

options:
  db:
    description: Database system
    default: postgresql
    choices:
      postgresql:
        description: PostgreSQL (recommended for production)
        variables:
          database: PostgreSQL
          db_adapter: asyncpg
      mysql:
        description: MySQL / MariaDB
        variables:
          database: MySQL
          db_adapter: aiomysql
      sqlite:
        description: SQLite (development only)
        variables:
          database: SQLite
          db_adapter: aiosqlite
      mongodb:
        description: MongoDB with Motor async driver
        patterns:
          - patterns/mongodb.md
        variables:
          database: MongoDB
          db_adapter: motor
          orm: Motor + Beanie

agents:
  - name: backend-developer
    template: agents/backend-developer.md.j2
    description: FastAPI backend developer
    model: opus
    tools:
      - Read
      - Write
      - Edit
      - Bash
      - Grep
      - Glob
    skills:
      - new-router
      - new-schema
      - new-model
      - new-service
      - new-migration
      - new-task

  - name: backend-tester
    template: agents/backend-tester.md.j2
    description: pytest testing specialist
    model: sonnet
    tools:
      - Read
      - Write
      - Edit
      - Bash
      - Grep
      - Glob
    skills:
      - new-test
      - test

  - name: backend-reviewer
    template: agents/backend-reviewer.md.j2
    description: Python/FastAPI code reviewer
    model: opus
    tools:
      - Read
      - Grep
      - Glob
      - Bash

skills:
  - test
  - review
  - docs
  - new-router
  - new-schema
  - new-model
  - new-service
  - new-migration
  - db-migrate
  - new-test
  - new-task
  - new-middleware
  - new-dependency

quality_gates:
  format:
    command: uv run ruff format --check src/ tests/
    fix_command: uv run ruff format src/ tests/
    description: Code formatting check
  lint:
    command: uv run ruff check src/ tests/
    fix_command: uv run ruff check --fix src/ tests/
    description: Ruff linting
  typecheck:
    command: uv run mypy src/
    description: Type checking with mypy
  tests:
    command: uv run pytest
    description: pytest test suite

working_dir: "."

patterns:
  - patterns/backend-patterns.md
  - patterns/oauth.md
  - patterns/pagination.md
  - patterns/rate-limiting.md
  - patterns/caching.md
  - patterns/logging.md
  - patterns/error-tracking.md

styles:
  - styles/backend-python.md
  - styles/async-patterns.md

variables:
  framework: FastAPI
  language: Python 3.12+
  test_framework: pytest + pytest-asyncio
  orm: SQLAlchemy 2.0 (async)
  validation: Pydantic v2
  migrations: Alembic (async)
  tasks: Celery
  database: PostgreSQL
  package_manager: uv
