name: fastapi
extends: python
display_name: Python FastAPI
description: Backend development with Python FastAPI

compatible_with:
  - nextjs
  - nuxt
  - react-native
  - scraping

agents:
  - name: backend-developer
    template: agents/backend-developer.md.j2
    description: FastAPI backend developer
    model: opus
    tools:
      - Read
      - Write
      - Edit
      - Bash
      - Grep
      - Glob
    skills:
      - new-router
      - new-schema
      - new-model
      - new-service
      - new-migration
      - new-task

  - name: backend-tester
    template: agents/backend-tester.md.j2
    description: pytest testing specialist
    model: sonnet
    tools:
      - Read
      - Write
      - Edit
      - Bash
      - Grep
      - Glob
    skills:
      - new-test
      - test

  - name: backend-reviewer
    template: agents/backend-reviewer.md.j2
    description: Python/FastAPI code reviewer
    model: opus
    tools:
      - Read
      - Grep
      - Glob
      - Bash

skills:
  - new-router
  - new-task
  - new-middleware
  - new-dependency

patterns:
  - patterns/fastapi-patterns.md
  - patterns/oauth.md
  - patterns/pagination.md
  - patterns/rate-limiting.md
  - patterns/caching.md
  - patterns/logging.md
  - patterns/error-tracking.md
  - patterns/verification.md

styles:
  - styles/async-patterns.md

variables:
  framework: FastAPI
  test_framework: pytest + pytest-asyncio
  tasks: Celery
  dev_port: 8000

verification:
  enabled: true
  auto_verify: true
  max_retries: 3
  dev_server:
    command: uv run uvicorn app.main:app --reload --port 8000
    port: 8000
    health_check: /docs
