name: nextjs
extends: javascript
display_name: React + Next.js
description: Frontend development with React and Next.js App Router

compatible_with:
  - rails
  - ruby
  - sinatra
  - fastapi
  - flask
  - python
  - django
  - express
  - scraping
  - go
  - gin
  - fiber
  - chi
  - elixir
  - phoenix

options:
  ui:
    description: UI component library
    default: mantine
    choices:
      mantine:
        description: Full-featured React component library
        styles:
          - styles/mantine.md
        variables:
          ui_library: Mantine v7+
      tailwind:
        description: Utility-first CSS framework
        styles:
          - styles/tailwind.md
        variables:
          ui_library: Tailwind CSS
      shadcn:
        description: Re-usable components built with Radix + Tailwind
        styles:
          - styles/shadcn.md
        variables:
          ui_library: shadcn/ui
      chakra:
        description: Simple, modular and accessible component library
        styles:
          - styles/chakra.md
        variables:
          ui_library: Chakra UI
      mui:
        description: Material Design components (Material UI)
        styles:
          - styles/mui.md
        variables:
          ui_library: Material UI (MUI)
      antd:
        description: Enterprise-class UI design language
        styles:
          - styles/antd.md
        variables:
          ui_library: Ant Design

  state:
    description: State management solution
    default: zustand
    choices:
      zustand:
        description: Lightweight, hooks-based state management
        patterns:
          - patterns/zustand.md
        skills:
          - new-store
        variables:
          state_library: Zustand
      redux:
        description: Predictable state container with Redux Toolkit
        patterns:
          - patterns/redux.md
        skills:
          - new-store
        variables:
          state_library: Redux Toolkit
      mobx:
        description: Observable-based reactive state management
        patterns:
          - patterns/mobx.md
        skills:
          - new-store
        variables:
          state_library: MobX
      jotai:
        description: Primitive and flexible atomic state management
        patterns:
          - patterns/jotai.md
        skills:
          - new-store
        variables:
          state_library: Jotai
      context:
        description: Built-in React Context API
        patterns:
          - patterns/context.md
        variables:
          state_library: React Context
      none:
        description: No global state management
        variables:
          state_library: None

agents:
  - name: frontend-developer
    template: agents/frontend-developer.md.j2
    description: Senior Next.js developer for production code
    model: opus
    tools:
      - Read
      - Write
      - Edit
      - Bash
      - Grep
      - Glob
    skills:
      - new-component
      - new-page
      - new-container
      - new-context
      - new-form
      - new-api-service

  - name: frontend-tester
    template: agents/frontend-tester.md.j2
    description: Jest + Playwright testing specialist
    model: sonnet
    tools:
      - Read
      - Write
      - Edit
      - Bash
      - Grep
      - Glob
    skills:
      - test

  - name: frontend-reviewer
    template: agents/frontend-reviewer.md.j2
    description: React/Next.js code reviewer
    model: opus
    tools:
      - Read
      - Grep
      - Glob
      - Bash

skills:
  - new-component
  - new-page
  - new-container
  - new-context
  - new-form
  - new-api-service
  - new-server-action
  - new-hook
  - new-layout
  - clone-page
  - analyze-site

patterns:
  - patterns/frontend-patterns.md
  - patterns/auth.md
  - patterns/pagination.md
  - patterns/i18n.md
  - patterns/logging.md
  - patterns/error-tracking.md
  - patterns/browser-cloning.md
  - patterns/verification.md

styles:
  - styles/frontend-typescript.md

variables:
  framework: Next.js 14+ (App Router)
  language: TypeScript
  test_framework: Jest + React Testing Library
  linter: ESLint + Prettier
  dev_port: 3000

verification:
  enabled: true
  auto_verify: true
  max_retries: 3
  dev_server:
    command: npm run dev
    port: 3000
  browser:
    headless: true
    viewport:
      width: 1280
      height: 720
